using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace StaticViewLocator;

[Generator(LanguageNames.CSharp)]
public sealed partial class StaticViewLocatorGenerator : IIncrementalGenerator
{
    private const string StaticViewLocatorAttributeDisplayString = "StaticViewLocator.StaticViewLocatorAttribute";
    private const string StaticViewMappingAttributeDisplayString = "StaticViewLocator.StaticViewMappingAttribute";
    private const string ViewModelSuffix = "ViewModel";
    private const string ViewSuffix = "View";
    private const string ViewModelNamespacePrefixesProperty = "build_property.StaticViewLocatorViewModelNamespacePrefixes";
    private const string IncludeInternalViewModelsProperty = "build_property.StaticViewLocatorIncludeInternalViewModels";
    private const string IncludeReferencedAssembliesProperty = "build_property.StaticViewLocatorIncludeReferencedAssemblies";
    private const string AdditionalViewBaseTypesProperty = "build_property.StaticViewLocatorAdditionalViewBaseTypes";
    private const string NamespaceReplacementRulesProperty = "build_property.StaticViewLocatorNamespaceReplacementRules";
    private const string TypeNameReplacementRulesProperty = "build_property.StaticViewLocatorTypeNameReplacementRules";
    private const string StripGenericArityFromViewNameProperty = "build_property.StaticViewLocatorStripGenericArityFromViewName";
    private const string InterfacePrefixesToStripProperty = "build_property.StaticViewLocatorInterfacePrefixesToStrip";

    private readonly struct GeneratorOptions
    {
        public GeneratorOptions(
            ImmutableArray<string> namespacePrefixes,
            bool includeInternalViewModels,
            bool includeReferencedAssemblies,
            ImmutableArray<string> additionalViewBaseTypes,
            ImmutableArray<ReplacementRule> namespaceReplacementRules,
            ImmutableArray<ReplacementRule> typeNameReplacementRules,
            bool stripGenericArityFromViewName,
            ImmutableArray<string> interfacePrefixesToStrip)
        {
            NamespacePrefixes = namespacePrefixes;
            IncludeInternalViewModels = includeInternalViewModels;
            IncludeReferencedAssemblies = includeReferencedAssemblies;
            AdditionalViewBaseTypes = additionalViewBaseTypes;
            NamespaceReplacementRules = namespaceReplacementRules;
            TypeNameReplacementRules = typeNameReplacementRules;
            StripGenericArityFromViewName = stripGenericArityFromViewName;
            InterfacePrefixesToStrip = interfacePrefixesToStrip;
        }

        public ImmutableArray<string> NamespacePrefixes { get; }
        public bool IncludeInternalViewModels { get; }
        public bool IncludeReferencedAssemblies { get; }
        public ImmutableArray<string> AdditionalViewBaseTypes { get; }
        public ImmutableArray<ReplacementRule> NamespaceReplacementRules { get; }
        public ImmutableArray<ReplacementRule> TypeNameReplacementRules { get; }
        public bool StripGenericArityFromViewName { get; }
        public ImmutableArray<string> InterfacePrefixesToStrip { get; }
    }

    private readonly struct ReplacementRule
    {
        public ReplacementRule(string from, string to)
        {
            From = from;
            To = to;
        }

        public string From { get; }
        public string To { get; }
    }

    private const string AttributeText =
        """
        // <auto-generated />
        using System;

        namespace StaticViewLocator;

        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class StaticViewLocatorAttribute : Attribute
        {
            public bool GenerateViewFactoryMethods { get; set; }

            public bool GenerateRuntimeTypeFallbackMethods { get; set; } = true;

            public bool GenerateIViewLocator { get; set; }

            public bool GenerateIDataTemplate { get; set; }

            public Type[] ViewModelMappingContracts { get; set; } = Array.Empty<Type>();

            public Type[] DataTemplateMatchTypes { get; set; } = Array.Empty<Type>();
        }

        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        public sealed class StaticViewMappingAttribute : Attribute
        {
            public StaticViewMappingAttribute(Type viewModelType, Type viewType)
            {
                ViewModelType = viewModelType;
                ViewType = viewType;
            }

            public Type ViewModelType { get; }

            public Type ViewType { get; }
        }

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("StaticViewLocatorAttribute.cs", SourceText.From(AttributeText, Encoding.UTF8)));

        var viewModelsProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) =>
                    node is TypeDeclarationSyntax typeDeclaration &&
                    (typeDeclaration is ClassDeclarationSyntax || typeDeclaration is InterfaceDeclarationSyntax) &&
                    typeDeclaration.Identifier.ValueText.EndsWith(ViewModelSuffix, StringComparison.Ordinal),
                static (generatorContext, cancellationToken) =>
                {
                    if (generatorContext.Node is not TypeDeclarationSyntax typeDeclaration ||
                        generatorContext.SemanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    return symbol;
                })
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!)
            .Collect();

        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => GetGeneratorOptions(options));

        var referencedViewModelsProvider = context.CompilationProvider
            .Combine(optionsProvider)
            .Select(static (pair, _) =>
                pair.Right.IncludeReferencedAssemblies
                    ? GetReferencedViewModels(pair.Left)
                    : ImmutableArray<INamedTypeSymbol>.Empty);

        var allViewModelsProvider = viewModelsProvider
            .Combine(referencedViewModelsProvider)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        var locatorsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            StaticViewLocatorAttributeDisplayString,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        var inputs = locatorsProvider
            .Combine(context.CompilationProvider)
            .Combine(allViewModelsProvider)
            .Combine(optionsProvider);

        context.RegisterSourceOutput(inputs, static (sourceProductionContext, tuple) =>
        {
            var (((locatorSymbol, compilation), viewModelSymbols), options) = tuple;

            var diagnostics = new List<Diagnostic>();
            var classSource = ProcessClass(compilation, locatorSymbol, viewModelSymbols, options, diagnostics);
            foreach (var diagnostic in diagnostics)
            {
                sourceProductionContext.ReportDiagnostic(diagnostic);
            }

            if (classSource is not null)
            {
                sourceProductionContext.AddSource(
                    GetGeneratedHintName(compilation, locatorSymbol),
                    SourceText.From(classSource, Encoding.UTF8));
            }
        });
    }

    private static ImmutableArray<INamedTypeSymbol> GetReferencedViewModels(Compilation compilation)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            CollectViewModels(assembly.GlobalNamespace, builder);
        }

        return builder.ToImmutable();
    }

    private static void CollectViewModels(INamespaceSymbol namespaceSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            CollectViewModels(type, builder);
        }

        foreach (var child in namespaceSymbol.GetNamespaceMembers())
        {
            CollectViewModels(child, builder);
        }
    }

    private static void CollectViewModels(INamedTypeSymbol typeSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        if (IsViewModelType(typeSymbol))
        {
            builder.Add(typeSymbol);
        }

        foreach (var nested in typeSymbol.GetTypeMembers())
        {
            CollectViewModels(nested, builder);
        }
    }

    private static GeneratorOptions GetGeneratorOptions(AnalyzerConfigOptionsProvider optionsProvider)
    {
        var namespacePrefixes = GetNamespacePrefixes(optionsProvider);
        var includeInternal = GetIncludeInternalViewModels(optionsProvider);
        var includeReferencedAssemblies = GetIncludeReferencedAssemblies(optionsProvider);
        var additionalViewBaseTypes = GetAdditionalViewBaseTypes(optionsProvider);
        var namespaceReplacementRules = GetReplacementRules(optionsProvider, NamespaceReplacementRulesProperty, new ReplacementRule("ViewModels", "Views"));
        var typeNameReplacementRules = GetReplacementRules(optionsProvider, TypeNameReplacementRulesProperty, new ReplacementRule(ViewModelSuffix, ViewSuffix));
        var stripGenericArityFromViewName = GetStripGenericArityFromViewName(optionsProvider);
        var interfacePrefixesToStrip = GetInterfacePrefixesToStrip(optionsProvider);

        return new GeneratorOptions(
            namespacePrefixes,
            includeInternal,
            includeReferencedAssemblies,
            additionalViewBaseTypes,
            namespaceReplacementRules,
            typeNameReplacementRules,
            stripGenericArityFromViewName,
            interfacePrefixesToStrip);
    }

    private static ImmutableArray<string> GetNamespacePrefixes(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(ViewModelNamespacePrefixesProperty, out var rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.ToImmutable();
    }

    private static bool GetIncludeInternalViewModels(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(IncludeInternalViewModelsProperty, out var rawValue))
        {
            return false;
        }

        return bool.TryParse(rawValue, out var includeInternal) && includeInternal;
    }

    private static bool GetIncludeReferencedAssemblies(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(IncludeReferencedAssembliesProperty, out var rawValue))
        {
            return false;
        }

        return bool.TryParse(rawValue, out var includeReferencedAssemblies) && includeReferencedAssemblies;
    }

    private static ImmutableArray<string> GetAdditionalViewBaseTypes(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(AdditionalViewBaseTypesProperty, out var rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.ToImmutable();
    }

    private static ImmutableArray<ReplacementRule> GetReplacementRules(
        AnalyzerConfigOptionsProvider optionsProvider,
        string propertyName,
        params ReplacementRule[] defaults)
    {
        var builder = ImmutableArray.CreateBuilder<ReplacementRule>();

        if (!optionsProvider.GlobalOptions.TryGetValue(propertyName, out var rawValue) ||
            string.IsNullOrWhiteSpace(rawValue))
        {
            foreach (var replacementRule in defaults)
            {
                builder.Add(replacementRule);
            }

            return builder.ToImmutable();
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length == 0)
            {
                continue;
            }

            var separatorIndex = trimmed.IndexOf('=');
            if (separatorIndex <= 0 || separatorIndex == trimmed.Length - 1)
            {
                continue;
            }

            var from = trimmed.Substring(0, separatorIndex).Trim();
            var to = trimmed.Substring(separatorIndex + 1).Trim();

            if (from.Length == 0)
            {
                continue;
            }

            builder.Add(new ReplacementRule(from, to));
        }

        foreach (var replacementRule in defaults)
        {
            builder.Add(replacementRule);
        }

        return builder.ToImmutable();
    }

    private static bool GetStripGenericArityFromViewName(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(StripGenericArityFromViewNameProperty, out var rawValue))
        {
            return true;
        }

        return !bool.TryParse(rawValue, out var stripGenericArityFromViewName) || stripGenericArityFromViewName;
    }

    private static ImmutableArray<string> GetInterfacePrefixesToStrip(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(InterfacePrefixesToStripProperty, out var rawValue) ||
            string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray.Create("I");
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.Count == 0 ? ImmutableArray.Create("I") : builder.ToImmutable();
    }

    private static bool IsViewModelType(INamedTypeSymbol symbol)
    {
        if (symbol.TypeKind != TypeKind.Class && symbol.TypeKind != TypeKind.Interface)
        {
            return false;
        }

        return symbol.Name.EndsWith(ViewModelSuffix, StringComparison.Ordinal);
    }

    private static bool IsViewModelCandidate(INamedTypeSymbol symbol, Compilation compilation, GeneratorOptions options)
    {
        if (!IsViewModelType(symbol))
        {
            return false;
        }

        if (!IsViewModelAccessible(symbol, compilation, options.IncludeInternalViewModels))
        {
            return false;
        }

        if (options.NamespacePrefixes.IsDefaultOrEmpty)
        {
            return true;
        }

        var namespaceName = GetNamespaceName(symbol.ContainingNamespace);
        if (namespaceName.Length == 0)
        {
            return false;
        }

        return MatchesNamespace(namespaceName, options.NamespacePrefixes);
    }

    private static bool IsViewModelAccessible(
        INamedTypeSymbol symbol,
        Compilation compilation,
        bool includeInternal)
    {
        if (SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, compilation.Assembly))
        {
            return true;
        }

        if (symbol.DeclaredAccessibility == Accessibility.Public && IsContainingTypesPublic(symbol))
        {
            return true;
        }

        if (!includeInternal || symbol.DeclaredAccessibility != Accessibility.Internal)
        {
            return false;
        }

        if (!IsContainingTypesAtMostInternal(symbol))
        {
            return false;
        }

        return symbol.ContainingAssembly.GivesAccessTo(compilation.Assembly);
    }

    private static bool IsContainingTypesPublic(INamedTypeSymbol symbol)
    {
        for (var containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            if (containing.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsContainingTypesAtMostInternal(INamedTypeSymbol symbol)
    {
        for (var containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            var accessibility = containing.DeclaredAccessibility;
            if (accessibility != Accessibility.Public && accessibility != Accessibility.Internal)
            {
                return false;
            }
        }

        return true;
    }

    private static bool MatchesNamespace(string namespaceName, ImmutableArray<string> namespacePrefixes)
    {
        foreach (var prefix in namespacePrefixes)
        {
            if (string.IsNullOrWhiteSpace(prefix))
            {
                continue;
            }

            var normalized = prefix.Trim();
            if (namespaceName.Equals(normalized, StringComparison.Ordinal) ||
                namespaceName.StartsWith(normalized + ".", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string ApplyReplacementRules(string input, ImmutableArray<ReplacementRule> replacementRules)
    {
        var value = input;

        foreach (var replacementRule in replacementRules)
        {
            value = value.Replace(replacementRule.From, replacementRule.To);
        }

        return value;
    }

    private static string GetMetadataTypeName(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.MetadataName);
        }

        return string.Join(".", parts);
    }

    private static string GetSourceTypeName(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.Name);
        }

        return string.Join(".", parts);
    }

    private static string GetSourceTypeReference(INamedTypeSymbol symbol)
    {
        if (HasConstructedGenericArguments(symbol))
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            var part = current.Name;
            if (current.IsGenericType)
            {
                part += "<" + new string(',', current.TypeParameters.Length - 1) + ">";
            }

            parts.Push(part);
        }

        var typeName = string.Join(".", parts);
        var namespaceName = GetNamespaceName(symbol.ContainingNamespace);
        return string.IsNullOrEmpty(namespaceName) ? typeName : $"{namespaceName}.{typeName}";
    }

    private static string CombineNamespaceAndType(string namespaceName, string typeName)
    {
        return string.IsNullOrEmpty(namespaceName) ? typeName : $"{namespaceName}.{typeName}";
    }

    private static string GetNamespaceName(INamespaceSymbol namespaceSymbol)
    {
        return namespaceSymbol.IsGlobalNamespace ? string.Empty : namespaceSymbol.ToDisplayString();
    }

    private static string GetGeneratedHintName(Compilation compilation, INamedTypeSymbol locatorSymbol)
    {
        var locatorCount = compilation.GetSymbolsWithName(locatorSymbol.Name, SymbolFilter.Type)
            .OfType<INamedTypeSymbol>()
            .Where(symbol =>
                SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, compilation.Assembly) &&
                symbol.ContainingSymbol.Equals(symbol.ContainingNamespace, SymbolEqualityComparer.Default) &&
                symbol.GetAttributes().Any(attribute =>
                    attribute.AttributeClass?.ToDisplayString() == StaticViewLocatorAttributeDisplayString))
            .Take(2)
            .Count();
        if (locatorCount < 2)
        {
            return $"{locatorSymbol.Name}_StaticViewLocator.cs";
        }

        var namespaceName = GetNamespaceName(locatorSymbol.ContainingNamespace);
        var identity = CombineNamespaceAndType(namespaceName, GetMetadataTypeName(locatorSymbol));
        var sanitized = new string(identity
            .Select(static character =>
                char.IsLetterOrDigit(character) || character is '.' or '_'
                    ? character
                    : '_')
            .ToArray());
        return $"{sanitized}_StaticViewLocator.cs";
    }

    private static bool HasConstructedGenericArguments(INamedTypeSymbol symbol)
    {
        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            foreach (var typeArgument in current.TypeArguments)
            {
                if (typeArgument is not ITypeParameterSymbol)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static string StripGenericArity(string typeName)
    {
        var parts = typeName.Split('.');

        for (var i = 0; i < parts.Length; i++)
        {
            var tickIndex = parts[i].IndexOf('`');
            if (tickIndex >= 0)
            {
                parts[i] = parts[i].Substring(0, tickIndex);
            }
        }

        return string.Join(".", parts);
    }

    private static string StripInterfacePrefix(string typeName, ImmutableArray<string> interfacePrefixesToStrip)
    {
        foreach (var prefix in interfacePrefixesToStrip)
        {
            if (string.IsNullOrEmpty(prefix))
            {
                continue;
            }

            var parts = typeName.Split('.');
            var last = parts[parts.Length - 1];
            if (!last.StartsWith(prefix, StringComparison.Ordinal) || last.Length <= prefix.Length)
            {
                continue;
            }

            parts[parts.Length - 1] = last.Substring(prefix.Length);
            return string.Join(".", parts);
        }

        return typeName;
    }

    private static string? ProcessClass(
        Compilation compilation,
        INamedTypeSymbol locatorSymbol,
        ImmutableArray<INamedTypeSymbol> viewModelSymbols,
        GeneratorOptions options,
        List<Diagnostic> diagnostics)
    {
        if (!locatorSymbol.ContainingSymbol.Equals(locatorSymbol.ContainingNamespace, SymbolEqualityComparer.Default))
        {
            diagnostics.Add(Diagnostic.Create(
                UnsupportedLocatorType,
                GetDiagnosticLocation(locatorSymbol),
                locatorSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                "nested"));
            return null;
        }

        var hasNonPartialDeclaration = locatorSymbol.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(static declaration => !declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
        if (locatorSymbol.IsStatic || locatorSymbol.IsFileLocal || hasNonPartialDeclaration)
        {
            diagnostics.Add(Diagnostic.Create(
                UnsupportedLocatorType,
                GetDiagnosticLocation(locatorSymbol),
                locatorSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                locatorSymbol.IsStatic
                    ? "static"
                    : locatorSymbol.IsFileLocal
                        ? "file-local"
                        : "not partial"));
            return null;
        }

        var namespaceNameLocator = GetNamespaceName(locatorSymbol.ContainingNamespace);
        var namespaceDeclaration = string.IsNullOrEmpty(namespaceNameLocator)
            ? string.Empty
            : $"namespace {namespaceNameLocator};\n\n";
        var locatorAccessibility = locatorSymbol.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";

        var buildMethodExists = locatorSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Any(method => method.Name == "Build" && method.Parameters.Length == 1);
        var generateIViewLocator = ShouldGenerateIViewLocator(locatorSymbol);
        var generateIDataTemplate = ShouldGenerateIDataTemplate(locatorSymbol);
        generateIViewLocator = ValidateReactiveUIAdapterTypes(
            compilation,
            locatorSymbol,
            diagnostics,
            generateIViewLocator);
        generateIDataTemplate = ValidateDataTemplateAdapterTypes(
            compilation,
            locatorSymbol,
            diagnostics,
            generateIDataTemplate);
        var dataTemplateBuildMethodExists = generateIDataTemplate &&
                                            HasDataTemplateBuildMethod(locatorSymbol, diagnostics);
        var dataTemplateMatchMethodExists = generateIDataTemplate &&
                                            HasDataTemplateMatchMethod(locatorSymbol, diagnostics);

        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters |
                             SymbolDisplayGenericsOptions.IncludeTypeConstraints |
                             SymbolDisplayGenericsOptions.IncludeVariance);

        var classNameLocator = locatorSymbol.ToDisplayString(format);

        var relevantViewModels = new List<INamedTypeSymbol>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var ambiguousViewModels = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var viewBaseTypes = GetViewBaseTypes(compilation, options);
        var explicitMappings = GetExplicitMappings(locatorSymbol);
        var inferredMappings = GetInferredMappings(
            compilation,
            locatorSymbol,
            viewBaseTypes,
            explicitMappings,
            diagnostics,
            ambiguousViewModels);
        if (generateIViewLocator)
        {
            foreach (var mapping in GetReactiveUIMappings(
                         compilation,
                         viewBaseTypes,
                         inferredMappings,
                         explicitMappings,
                         diagnostics,
                         ambiguousViewModels))
            {
                if (!inferredMappings.ContainsKey(mapping.Key))
                {
                    inferredMappings.Add(mapping.Key, mapping.Value);
                }
            }
        }
        foreach (var mapping in explicitMappings)
        {
            inferredMappings[mapping.Key] = mapping.Value;
        }

        foreach (var symbol in viewModelSymbols)
        {
            if (!IsViewModelCandidate(symbol, compilation, options) ||
                ambiguousViewModels.Contains(symbol))
            {
                continue;
            }

            if (seen.Add(symbol))
            {
                relevantViewModels.Add(symbol);
            }
        }

        foreach (var mapping in inferredMappings)
        {
            if (seen.Add(mapping.Key))
            {
                relevantViewModels.Add(mapping.Key);
            }
        }

        relevantViewModels.Sort(static (left, right) =>
            string.Compare(left.ToDisplayString(), right.ToDisplayString(), StringComparison.Ordinal));

        var generatedInterfacesClause = GetGeneratedInterfacesClause(
            locatorSymbol,
            generateIViewLocator,
            generateIDataTemplate);

        var source = new StringBuilder(
            $$"""
            // <auto-generated />
            #nullable enable
            using System;
            using System.Collections.Generic;
            using Avalonia.Controls;

            {{namespaceDeclaration}}{{locatorAccessibility}} partial class {{classNameLocator}}{{generatedInterfacesClause}}
            {
            """);

        source.AppendLine();
        source.AppendLine("\tprivate static Dictionary<Type, Func<Control>> s_views = new()");
        source.AppendLine("\t{");

        foreach (var viewModelSymbol in relevantViewModels)
        {
            var namespaceNameViewModel = GetNamespaceName(viewModelSymbol.ContainingNamespace);
            var sourceTypeNameViewModel = GetSourceTypeName(viewModelSymbol);
            var metadataTypeNameViewModel = GetMetadataTypeName(viewModelSymbol);

            var sourceNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);
            var metadataNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);

            var sourceTypeNameView = ApplyReplacementRules(sourceTypeNameViewModel, options.TypeNameReplacementRules);
            var metadataTypeNameView = ApplyReplacementRules(metadataTypeNameViewModel, options.TypeNameReplacementRules);

            if (viewModelSymbol.TypeKind == TypeKind.Interface)
            {
                sourceTypeNameView = StripInterfacePrefix(sourceTypeNameView, options.InterfacePrefixesToStrip);
                metadataTypeNameView = StripInterfacePrefix(metadataTypeNameView, options.InterfacePrefixesToStrip);
            }

            if (options.StripGenericArityFromViewName)
            {
                sourceTypeNameView = StripGenericArity(sourceTypeNameView);
                metadataTypeNameView = StripGenericArity(metadataTypeNameView);
            }

            var classNameViewModel = GetSourceTypeReference(viewModelSymbol);
            var classNameView = CombineNamespaceAndType(sourceNamespaceView, sourceTypeNameView);
            var metadataNameView = CombineNamespaceAndType(metadataNamespaceView, metadataTypeNameView);

            INamedTypeSymbol? viewSymbol;
            if (inferredMappings.TryGetValue(viewModelSymbol, out var explicitViewSymbol))
            {
                viewSymbol = explicitViewSymbol;
                classNameView = GetSourceTypeReference(explicitViewSymbol);
            }
            else
            {
                viewSymbol = compilation.GetTypeByMetadataName(metadataNameView);
            }
            var isSupportedView = viewSymbol is not null && IsSupportedView(viewSymbol, viewBaseTypes);

            if (viewSymbol is null || !isSupportedView)
            {
                continue;
            }

            if (viewSymbol.IsGenericType)
            {
                continue;
            }

            if (!CanInstantiateView(compilation, locatorSymbol, viewSymbol))
            {
                diagnostics.Add(Diagnostic.Create(
                    ViewCannotBeConstructed,
                    GetDiagnosticLocation(viewSymbol),
                    viewSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                    viewModelSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)));
                continue;
            }

            source.AppendLine($"\t\t[typeof({classNameViewModel})] = () => new {classNameView}(),");
        }

        source.AppendLine("\t};");
        source.AppendLine();
        source.AppendLine("\tprivate static Dictionary<Type, string> s_missingViews = new()");
        source.AppendLine("\t{");

        foreach (var viewModelSymbol in relevantViewModels)
        {
            var namespaceNameViewModel = GetNamespaceName(viewModelSymbol.ContainingNamespace);
            var sourceTypeNameViewModel = GetSourceTypeName(viewModelSymbol);
            var metadataTypeNameViewModel = GetMetadataTypeName(viewModelSymbol);

            var sourceNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);
            var metadataNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);

            var sourceTypeNameView = ApplyReplacementRules(sourceTypeNameViewModel, options.TypeNameReplacementRules);
            var metadataTypeNameView = ApplyReplacementRules(metadataTypeNameViewModel, options.TypeNameReplacementRules);

            if (viewModelSymbol.TypeKind == TypeKind.Interface)
            {
                sourceTypeNameView = StripInterfacePrefix(sourceTypeNameView, options.InterfacePrefixesToStrip);
                metadataTypeNameView = StripInterfacePrefix(metadataTypeNameView, options.InterfacePrefixesToStrip);
            }

            if (options.StripGenericArityFromViewName)
            {
                sourceTypeNameView = StripGenericArity(sourceTypeNameView);
                metadataTypeNameView = StripGenericArity(metadataTypeNameView);
            }

            var classNameViewModel = GetSourceTypeReference(viewModelSymbol);
            var classNameView = CombineNamespaceAndType(sourceNamespaceView, sourceTypeNameView);
            var metadataNameView = CombineNamespaceAndType(metadataNamespaceView, metadataTypeNameView);

            INamedTypeSymbol? viewSymbol;
            if (inferredMappings.TryGetValue(viewModelSymbol, out var explicitViewSymbol))
            {
                viewSymbol = explicitViewSymbol;
                classNameView = GetSourceTypeReference(explicitViewSymbol);
            }
            else
            {
                viewSymbol = compilation.GetTypeByMetadataName(metadataNameView);
            }
            var isSupportedView = viewSymbol is not null && IsSupportedView(viewSymbol, viewBaseTypes);

            if (viewSymbol is not null &&
                isSupportedView &&
                (viewSymbol.IsGenericType || CanInstantiateView(compilation, locatorSymbol, viewSymbol)))
            {
                continue;
            }

            source.AppendLine(
                $"\t\t[typeof({classNameViewModel})] = \"Not Found: {classNameView}\",");
        }

        source.AppendLine("\t};");

        if ((ShouldGenerateViewFactoryMethods(locatorSymbol) || generateIViewLocator || generateIDataTemplate) &&
            !HasTryCreateViewExact(locatorSymbol, diagnostics))
        {
            source.Append(
                """

	private static bool TryCreateViewExact(Type viewModelType, out Control? view)
	{
		if (s_views.TryGetValue(viewModelType, out var factory))
		{
			view = factory();
			return true;
		}

		view = null;
		return false;
	}
""");
            source.AppendLine();
        }

        if (generateIViewLocator)
        {
            AppendIViewLocator(source, locatorSymbol, diagnostics);
        }

        if (!buildMethodExists && !generateIDataTemplate)
        {
            source.Append(
                """

	public Control? Build(object? data)
	{
		if (data is null)
		{
			return null;
		}

		var type = data.GetType();
		var func = TryGetFactory(type) ?? TryGetFactoryFromInterfaces(type);

		if (func is not null)
		{
			return func.Invoke();
		}

		var missingView = TryGetMissingView(type) ?? TryGetMissingViewFromInterfaces(type);
		if (missingView is not null)
		{
			return new TextBlock { Text = missingView };
		}

		throw new Exception($"Unable to create view for type: {type}");
	}

""");
        }

        if (!dataTemplateBuildMethodExists && generateIDataTemplate)
        {
            AppendDataTemplateBuild(source, compilation, locatorSymbol, generateIViewLocator, diagnostics);
        }

        if (generateIDataTemplate && !dataTemplateMatchMethodExists)
        {
            AppendDataTemplateMatch(source, locatorSymbol, diagnostics);
        }

        var shouldGenerateRuntimeFallbackMethods =
            (!buildMethodExists && !generateIDataTemplate) ||
            ((generateIDataTemplate ? dataTemplateBuildMethodExists : buildMethodExists) &&
             ShouldGenerateRuntimeTypeFallbackMethods(locatorSymbol));
        if (shouldGenerateRuntimeFallbackMethods)
        {
            source.Append(
                """

	private static Func<Control>? TryGetFactory(Type? type)
	{
		if (type is null)
		{
			return null;
		}

		if (TryGetFactoryForType(type, out var func))
		{
			return func;
		}

		for (var current = type.BaseType; current is not null; current = current.BaseType)
		{
			if (TryGetFactoryForType(current, out func))
			{
				return func;
			}
		}

		return null;
	}

	private static Func<Control>? TryGetFactoryFromInterfaces(Type type)
	{
		var interfaces = type.GetInterfaces();
		for (var index = interfaces.Length - 1; index >= 0; index--)
		{
			var interfaceType = interfaces[index];
			if (!interfaceType.Name.EndsWith("ViewModel", StringComparison.Ordinal))
			{
				continue;
			}

			if (TryGetFactoryForType(interfaceType, out var func))
			{
				return func;
			}
		}

		return null;
	}

	private static bool TryGetFactoryForType(Type type, out Func<Control>? func)
	{
		if (s_views.TryGetValue(type, out func))
		{
			return true;
		}

		if (type.IsGenericType && s_views.TryGetValue(type.GetGenericTypeDefinition(), out func))
		{
			return true;
		}

		func = null;
		return false;
	}

	private static string? TryGetMissingView(Type? type)
	{
		if (type is null)
		{
			return null;
		}

		if (TryGetMissingViewForType(type, out var missingView))
		{
			return missingView;
		}

		for (var current = type.BaseType; current is not null; current = current.BaseType)
		{
			if (TryGetMissingViewForType(current, out missingView))
			{
				return missingView;
			}
		}

		return null;
	}

	private static string? TryGetMissingViewFromInterfaces(Type type)
	{
		var interfaces = type.GetInterfaces();
		for (var index = interfaces.Length - 1; index >= 0; index--)
		{
			var interfaceType = interfaces[index];
			if (!interfaceType.Name.EndsWith("ViewModel", StringComparison.Ordinal))
			{
				continue;
			}

			if (TryGetMissingViewForType(interfaceType, out var missingView))
			{
				return missingView;
			}
		}

		return null;
	}

	private static bool TryGetMissingViewForType(Type type, out string? missingView)
	{
		if (s_missingViews.TryGetValue(type, out missingView))
		{
			return true;
		}

		if (type.IsGenericType && s_missingViews.TryGetValue(type.GetGenericTypeDefinition(), out missingView))
		{
			return true;
		}

		missingView = null;
		return false;
	}

""");
        }

        source.AppendLine("}");

        return source.ToString();
    }

    private static Dictionary<INamedTypeSymbol, INamedTypeSymbol> GetExplicitMappings(INamedTypeSymbol locatorSymbol)
    {
        var mappings = new Dictionary<INamedTypeSymbol, INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var attribute in locatorSymbol.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != StaticViewMappingAttributeDisplayString ||
                attribute.ConstructorArguments.Length != 2 ||
                attribute.ConstructorArguments[0].Value is not INamedTypeSymbol viewModelType ||
                attribute.ConstructorArguments[1].Value is not INamedTypeSymbol viewType)
            {
                continue;
            }

            mappings[viewModelType] = viewType;
        }

        return mappings;
    }

    private static HashSet<INamedTypeSymbol> GetViewBaseTypes(Compilation compilation, GeneratorOptions options)
    {
        var viewBaseTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        AddTypeIfFound("Avalonia.Controls.UserControl");
        AddTypeIfFound("Avalonia.Controls.Window");

        foreach (var additionalTypeName in options.AdditionalViewBaseTypes)
        {
            AddTypeIfFound(additionalTypeName);
        }

        return viewBaseTypes;

        void AddTypeIfFound(string metadataName)
        {
            var symbol = compilation.GetTypeByMetadataName(metadataName);
            if (symbol is not null)
            {
                viewBaseTypes.Add(symbol);
            }
        }
    }

    private static Dictionary<INamedTypeSymbol, INamedTypeSymbol> GetInferredMappings(
        Compilation compilation,
        INamedTypeSymbol locatorSymbol,
        HashSet<INamedTypeSymbol> viewBaseTypes,
        IReadOnlyDictionary<INamedTypeSymbol, INamedTypeSymbol> explicitMappings,
        ICollection<Diagnostic> diagnostics,
        HashSet<INamedTypeSymbol> ambiguousViewModels)
    {
        var contracts = GetViewModelMappingContracts(locatorSymbol);
        var mappings = new Dictionary<INamedTypeSymbol, INamedTypeSymbol>(SymbolEqualityComparer.Default);
        if (contracts.Count == 0)
        {
            return mappings;
        }

        var types = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        CollectTypes(compilation.Assembly.GlobalNamespace, types);

        foreach (var viewType in types
                     .Where(type => type.TypeKind == TypeKind.Class && !type.IsAbstract && !type.IsGenericType)
                     .OrderBy(type => type.ToDisplayString(), StringComparer.Ordinal))
        {
            if (!IsSupportedView(viewType, viewBaseTypes) ||
                !TryGetMappedViewModelType(viewType, contracts, out var viewModelType))
            {
                continue;
            }

            if (explicitMappings.ContainsKey(viewModelType))
            {
                continue;
            }

            if (ambiguousViewModels.Contains(viewModelType))
            {
                continue;
            }

            if (mappings.TryGetValue(viewModelType, out var existingView))
            {
                if (!SymbolEqualityComparer.Default.Equals(existingView, viewType))
                {
                    diagnostics.Add(Diagnostic.Create(
                        AmbiguousViewMapping,
                        GetDiagnosticLocation(viewType),
                        viewModelType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                        existingView.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                        viewType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)));
                    mappings.Remove(viewModelType);
                    ambiguousViewModels.Add(viewModelType);
                }

                continue;
            }

            mappings.Add(viewModelType, viewType);
        }

        return mappings;
    }

    private static HashSet<INamedTypeSymbol> GetViewModelMappingContracts(INamedTypeSymbol locatorSymbol)
    {
        var contracts = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var locatorAttribute = locatorSymbol.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == StaticViewLocatorAttributeDisplayString);
        if (locatorAttribute is null)
        {
            return contracts;
        }

        foreach (var argument in locatorAttribute.NamedArguments)
        {
            if (argument.Key != "ViewModelMappingContracts" || argument.Value.Kind != TypedConstantKind.Array)
            {
                continue;
            }

            foreach (var value in argument.Value.Values)
            {
                if (value.Value is INamedTypeSymbol contract && contract.Arity == 1)
                {
                    contracts.Add(contract.OriginalDefinition);
                }
            }
        }

        return contracts;
    }

    private static bool TryGetMappedViewModelType(
        INamedTypeSymbol viewType,
        HashSet<INamedTypeSymbol> contracts,
        out INamedTypeSymbol viewModelType)
    {
        foreach (var interfaceType in viewType.AllInterfaces)
        {
            if (TryGetContractTypeArgument(interfaceType, contracts, out viewModelType))
            {
                return true;
            }
        }

        for (var current = viewType.BaseType; current is not null; current = current.BaseType)
        {
            if (TryGetContractTypeArgument(current, contracts, out viewModelType))
            {
                return true;
            }
        }

        viewModelType = null!;
        return false;
    }

    private static bool TryGetContractTypeArgument(
        INamedTypeSymbol candidate,
        HashSet<INamedTypeSymbol> contracts,
        out INamedTypeSymbol viewModelType)
    {
        if (candidate.TypeArguments.Length == 1 &&
            contracts.Contains(candidate.OriginalDefinition) &&
            candidate.TypeArguments[0] is INamedTypeSymbol namedType)
        {
            viewModelType = namedType;
            return true;
        }

        viewModelType = null!;
        return false;
    }

    private static void CollectTypes(INamespaceSymbol namespaceSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            CollectTypes(type, builder);
        }

        foreach (var child in namespaceSymbol.GetNamespaceMembers())
        {
            CollectTypes(child, builder);
        }
    }

    private static void CollectTypes(INamedTypeSymbol typeSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        builder.Add(typeSymbol);

        foreach (var nested in typeSymbol.GetTypeMembers())
        {
            CollectTypes(nested, builder);
        }
    }

    private static bool IsSupportedView(
        INamedTypeSymbol viewSymbol,
        HashSet<INamedTypeSymbol> viewBaseTypes)
    {
        for (var current = viewSymbol; current is not null; current = current.BaseType)
        {
            if (viewBaseTypes.Contains(current))
            {
                return true;
            }
        }

        return false;
    }

    private static bool CanInstantiateView(
        Compilation compilation,
        INamedTypeSymbol locatorSymbol,
        INamedTypeSymbol viewSymbol)
    {
        if (viewSymbol.TypeKind != TypeKind.Class ||
            viewSymbol.IsAbstract ||
            viewSymbol.IsStatic ||
            viewSymbol.IsGenericType ||
            !compilation.IsSymbolAccessibleWithin(viewSymbol, locatorSymbol))
        {
            return false;
        }

        return viewSymbol.InstanceConstructors.Any(constructor =>
            compilation.IsSymbolAccessibleWithin(constructor, locatorSymbol) &&
            constructor.Parameters.All(static parameter => parameter.IsOptional || parameter.IsParams));
    }

    private static bool ShouldGenerateViewFactoryMethods(INamedTypeSymbol locatorSymbol)
    {
        var locatorAttribute = locatorSymbol.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == StaticViewLocatorAttributeDisplayString);
        if (locatorAttribute is null)
        {
            return false;
        }

        foreach (var argument in locatorAttribute.NamedArguments)
        {
            if (argument.Key == "GenerateViewFactoryMethods" && argument.Value.Value is true)
            {
                return true;
            }
        }

        return false;
    }

    private static bool ShouldGenerateRuntimeTypeFallbackMethods(INamedTypeSymbol locatorSymbol)
    {
        var locatorAttribute = locatorSymbol.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == StaticViewLocatorAttributeDisplayString);
        if (locatorAttribute is null)
        {
            return true;
        }

        foreach (var argument in locatorAttribute.NamedArguments)
        {
            if (argument.Key == "GenerateRuntimeTypeFallbackMethods" && argument.Value.Value is bool value)
            {
                return value;
            }
        }

        return true;
    }
}
