using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace StaticViewLocator;

[Generator(LanguageNames.CSharp)]
public sealed class StaticViewLocatorGenerator : IIncrementalGenerator
{
    private const string StaticViewLocatorAttributeDisplayString = "StaticViewLocator.StaticViewLocatorAttribute";
    private const string ViewModelSuffix = "ViewModel";
    private const string ViewSuffix = "View";
    private const string ViewModelNamespacePrefixesProperty = "build_property.StaticViewLocatorViewModelNamespacePrefixes";
    private const string IncludeInternalViewModelsProperty = "build_property.StaticViewLocatorIncludeInternalViewModels";
    private const string IncludeReferencedAssembliesProperty = "build_property.StaticViewLocatorIncludeReferencedAssemblies";
    private const string AdditionalViewBaseTypesProperty = "build_property.StaticViewLocatorAdditionalViewBaseTypes";
    private const string NamespaceReplacementRulesProperty = "build_property.StaticViewLocatorNamespaceReplacementRules";
    private const string TypeNameReplacementRulesProperty = "build_property.StaticViewLocatorTypeNameReplacementRules";
    private const string StripGenericArityFromViewNameProperty = "build_property.StaticViewLocatorStripGenericArityFromViewName";
    private const string InterfacePrefixesToStripProperty = "build_property.StaticViewLocatorInterfacePrefixesToStrip";

    private readonly struct GeneratorOptions
    {
        public GeneratorOptions(
            ImmutableArray<string> namespacePrefixes,
            bool includeInternalViewModels,
            bool includeReferencedAssemblies,
            ImmutableArray<string> additionalViewBaseTypes,
            ImmutableArray<ReplacementRule> namespaceReplacementRules,
            ImmutableArray<ReplacementRule> typeNameReplacementRules,
            bool stripGenericArityFromViewName,
            ImmutableArray<string> interfacePrefixesToStrip)
        {
            NamespacePrefixes = namespacePrefixes;
            IncludeInternalViewModels = includeInternalViewModels;
            IncludeReferencedAssemblies = includeReferencedAssemblies;
            AdditionalViewBaseTypes = additionalViewBaseTypes;
            NamespaceReplacementRules = namespaceReplacementRules;
            TypeNameReplacementRules = typeNameReplacementRules;
            StripGenericArityFromViewName = stripGenericArityFromViewName;
            InterfacePrefixesToStrip = interfacePrefixesToStrip;
        }

        public ImmutableArray<string> NamespacePrefixes { get; }
        public bool IncludeInternalViewModels { get; }
        public bool IncludeReferencedAssemblies { get; }
        public ImmutableArray<string> AdditionalViewBaseTypes { get; }
        public ImmutableArray<ReplacementRule> NamespaceReplacementRules { get; }
        public ImmutableArray<ReplacementRule> TypeNameReplacementRules { get; }
        public bool StripGenericArityFromViewName { get; }
        public ImmutableArray<string> InterfacePrefixesToStrip { get; }
    }

    private readonly struct ReplacementRule
    {
        public ReplacementRule(string from, string to)
        {
            From = from;
            To = to;
        }

        public string From { get; }
        public string To { get; }
    }

    private const string AttributeText =
        """
        // <auto-generated />
        using System;

        namespace StaticViewLocator;

        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class StaticViewLocatorAttribute : Attribute
        {
        }

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("StaticViewLocatorAttribute.cs", SourceText.From(AttributeText, Encoding.UTF8)));

        var viewModelsProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) =>
                    node is TypeDeclarationSyntax typeDeclaration &&
                    (typeDeclaration is ClassDeclarationSyntax || typeDeclaration is InterfaceDeclarationSyntax) &&
                    typeDeclaration.Identifier.ValueText.EndsWith(ViewModelSuffix, StringComparison.Ordinal),
                static (generatorContext, cancellationToken) =>
                {
                    if (generatorContext.Node is not TypeDeclarationSyntax typeDeclaration ||
                        generatorContext.SemanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    return symbol;
                })
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!)
            .Collect();

        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => GetGeneratorOptions(options));

        var referencedViewModelsProvider = context.CompilationProvider
            .Combine(optionsProvider)
            .Select(static (pair, _) =>
                pair.Right.IncludeReferencedAssemblies
                    ? GetReferencedViewModels(pair.Left)
                    : ImmutableArray<INamedTypeSymbol>.Empty);

        var allViewModelsProvider = viewModelsProvider
            .Combine(referencedViewModelsProvider)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));

        var locatorsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            StaticViewLocatorAttributeDisplayString,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        var inputs = locatorsProvider
            .Combine(context.CompilationProvider)
            .Combine(allViewModelsProvider)
            .Combine(optionsProvider);

        context.RegisterSourceOutput(inputs, static (sourceProductionContext, tuple) =>
        {
            var (((locatorSymbol, compilation), viewModelSymbols), options) = tuple;

            var classSource = ProcessClass(compilation, locatorSymbol, viewModelSymbols, options);
            if (classSource is not null)
            {
                sourceProductionContext.AddSource(
                    $"{locatorSymbol.Name}_StaticViewLocator.cs",
                    SourceText.From(classSource, Encoding.UTF8));
            }
        });
    }

    private static ImmutableArray<INamedTypeSymbol> GetReferencedViewModels(Compilation compilation)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            CollectViewModels(assembly.GlobalNamespace, builder);
        }

        return builder.ToImmutable();
    }

    private static void CollectViewModels(INamespaceSymbol namespaceSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            CollectViewModels(type, builder);
        }

        foreach (var child in namespaceSymbol.GetNamespaceMembers())
        {
            CollectViewModels(child, builder);
        }
    }

    private static void CollectViewModels(INamedTypeSymbol typeSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        if (IsViewModelType(typeSymbol))
        {
            builder.Add(typeSymbol);
        }

        foreach (var nested in typeSymbol.GetTypeMembers())
        {
            CollectViewModels(nested, builder);
        }
    }

    private static GeneratorOptions GetGeneratorOptions(AnalyzerConfigOptionsProvider optionsProvider)
    {
        var namespacePrefixes = GetNamespacePrefixes(optionsProvider);
        var includeInternal = GetIncludeInternalViewModels(optionsProvider);
        var includeReferencedAssemblies = GetIncludeReferencedAssemblies(optionsProvider);
        var additionalViewBaseTypes = GetAdditionalViewBaseTypes(optionsProvider);
        var namespaceReplacementRules = GetReplacementRules(optionsProvider, NamespaceReplacementRulesProperty, new ReplacementRule("ViewModels", "Views"));
        var typeNameReplacementRules = GetReplacementRules(optionsProvider, TypeNameReplacementRulesProperty, new ReplacementRule(ViewModelSuffix, ViewSuffix));
        var stripGenericArityFromViewName = GetStripGenericArityFromViewName(optionsProvider);
        var interfacePrefixesToStrip = GetInterfacePrefixesToStrip(optionsProvider);

        return new GeneratorOptions(
            namespacePrefixes,
            includeInternal,
            includeReferencedAssemblies,
            additionalViewBaseTypes,
            namespaceReplacementRules,
            typeNameReplacementRules,
            stripGenericArityFromViewName,
            interfacePrefixesToStrip);
    }

    private static ImmutableArray<string> GetNamespacePrefixes(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(ViewModelNamespacePrefixesProperty, out var rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.ToImmutable();
    }

    private static bool GetIncludeInternalViewModels(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(IncludeInternalViewModelsProperty, out var rawValue))
        {
            return false;
        }

        return bool.TryParse(rawValue, out var includeInternal) && includeInternal;
    }

    private static bool GetIncludeReferencedAssemblies(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(IncludeReferencedAssembliesProperty, out var rawValue))
        {
            return false;
        }

        return bool.TryParse(rawValue, out var includeReferencedAssemblies) && includeReferencedAssemblies;
    }

    private static ImmutableArray<string> GetAdditionalViewBaseTypes(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(AdditionalViewBaseTypesProperty, out var rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.ToImmutable();
    }

    private static ImmutableArray<ReplacementRule> GetReplacementRules(
        AnalyzerConfigOptionsProvider optionsProvider,
        string propertyName,
        params ReplacementRule[] defaults)
    {
        var builder = ImmutableArray.CreateBuilder<ReplacementRule>();

        if (!optionsProvider.GlobalOptions.TryGetValue(propertyName, out var rawValue) ||
            string.IsNullOrWhiteSpace(rawValue))
        {
            foreach (var replacementRule in defaults)
            {
                builder.Add(replacementRule);
            }

            return builder.ToImmutable();
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length == 0)
            {
                continue;
            }

            var separatorIndex = trimmed.IndexOf('=');
            if (separatorIndex <= 0 || separatorIndex == trimmed.Length - 1)
            {
                continue;
            }

            var from = trimmed.Substring(0, separatorIndex).Trim();
            var to = trimmed.Substring(separatorIndex + 1).Trim();

            if (from.Length == 0)
            {
                continue;
            }

            builder.Add(new ReplacementRule(from, to));
        }

        foreach (var replacementRule in defaults)
        {
            builder.Add(replacementRule);
        }

        return builder.ToImmutable();
    }

    private static bool GetStripGenericArityFromViewName(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(StripGenericArityFromViewNameProperty, out var rawValue))
        {
            return true;
        }

        return !bool.TryParse(rawValue, out var stripGenericArityFromViewName) || stripGenericArityFromViewName;
    }

    private static ImmutableArray<string> GetInterfacePrefixesToStrip(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(InterfacePrefixesToStripProperty, out var rawValue) ||
            string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray.Create("I");
        }

        var parts = rawValue.Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries);
        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.Count == 0 ? ImmutableArray.Create("I") : builder.ToImmutable();
    }

    private static bool IsViewModelType(INamedTypeSymbol symbol)
    {
        if (symbol.TypeKind != TypeKind.Class && symbol.TypeKind != TypeKind.Interface)
        {
            return false;
        }

        return symbol.Name.EndsWith(ViewModelSuffix, StringComparison.Ordinal);
    }

    private static bool IsViewModelCandidate(INamedTypeSymbol symbol, Compilation compilation, GeneratorOptions options)
    {
        if (!IsViewModelType(symbol))
        {
            return false;
        }

        if (!IsViewModelAccessible(symbol, compilation, options.IncludeInternalViewModels))
        {
            return false;
        }

        if (options.NamespacePrefixes.IsDefaultOrEmpty)
        {
            return true;
        }

        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        if (namespaceName.Length == 0)
        {
            return false;
        }

        return MatchesNamespace(namespaceName, options.NamespacePrefixes);
    }

    private static bool IsViewModelAccessible(
        INamedTypeSymbol symbol,
        Compilation compilation,
        bool includeInternal)
    {
        if (SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, compilation.Assembly))
        {
            return true;
        }

        if (symbol.DeclaredAccessibility == Accessibility.Public && IsContainingTypesPublic(symbol))
        {
            return true;
        }

        if (!includeInternal || symbol.DeclaredAccessibility != Accessibility.Internal)
        {
            return false;
        }

        if (!IsContainingTypesAtMostInternal(symbol))
        {
            return false;
        }

        return symbol.ContainingAssembly.GivesAccessTo(compilation.Assembly);
    }

    private static bool IsContainingTypesPublic(INamedTypeSymbol symbol)
    {
        for (var containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            if (containing.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsContainingTypesAtMostInternal(INamedTypeSymbol symbol)
    {
        for (var containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            var accessibility = containing.DeclaredAccessibility;
            if (accessibility != Accessibility.Public && accessibility != Accessibility.Internal)
            {
                return false;
            }
        }

        return true;
    }

    private static bool MatchesNamespace(string namespaceName, ImmutableArray<string> namespacePrefixes)
    {
        foreach (var prefix in namespacePrefixes)
        {
            if (string.IsNullOrWhiteSpace(prefix))
            {
                continue;
            }

            var normalized = prefix.Trim();
            if (namespaceName.Equals(normalized, StringComparison.Ordinal) ||
                namespaceName.StartsWith(normalized + ".", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string ApplyReplacementRules(string input, ImmutableArray<ReplacementRule> replacementRules)
    {
        var value = input;

        foreach (var replacementRule in replacementRules)
        {
            value = value.Replace(replacementRule.From, replacementRule.To);
        }

        return value;
    }

    private static string GetMetadataTypeName(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.MetadataName);
        }

        return string.Join(".", parts);
    }

    private static string GetSourceTypeName(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.Name);
        }

        return string.Join(".", parts);
    }

    private static string GetSourceTypeReference(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            var part = current.Name;
            if (current.IsGenericType)
            {
                part += "<" + new string(',', current.TypeParameters.Length - 1) + ">";
            }

            parts.Push(part);
        }

        var typeName = string.Join(".", parts);
        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        return string.IsNullOrEmpty(namespaceName) ? typeName : $"{namespaceName}.{typeName}";
    }

    private static string StripGenericArity(string typeName)
    {
        var parts = typeName.Split('.');

        for (var i = 0; i < parts.Length; i++)
        {
            var tickIndex = parts[i].IndexOf('`');
            if (tickIndex >= 0)
            {
                parts[i] = parts[i].Substring(0, tickIndex);
            }
        }

        return string.Join(".", parts);
    }

    private static string StripInterfacePrefix(string typeName, ImmutableArray<string> interfacePrefixesToStrip)
    {
        foreach (var prefix in interfacePrefixesToStrip)
        {
            if (string.IsNullOrEmpty(prefix))
            {
                continue;
            }

            var parts = typeName.Split('.');
            var last = parts[parts.Length - 1];
            if (!last.StartsWith(prefix, StringComparison.Ordinal) || last.Length <= prefix.Length)
            {
                continue;
            }

            parts[parts.Length - 1] = last.Substring(prefix.Length);
            return string.Join(".", parts);
        }

        return typeName;
    }

    private static string? ProcessClass(
        Compilation compilation,
        INamedTypeSymbol locatorSymbol,
        ImmutableArray<INamedTypeSymbol> viewModelSymbols,
        GeneratorOptions options)
    {
        if (!locatorSymbol.ContainingSymbol.Equals(locatorSymbol.ContainingNamespace, SymbolEqualityComparer.Default))
        {
            return null;
        }

        var namespaceNameLocator = locatorSymbol.ContainingNamespace.ToDisplayString();

        var buildMethodExists = locatorSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Any(method => method.Name == "Build" && method.Parameters.Length == 1);

        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters |
                             SymbolDisplayGenericsOptions.IncludeTypeConstraints |
                             SymbolDisplayGenericsOptions.IncludeVariance);

        var classNameLocator = locatorSymbol.ToDisplayString(format);

        var relevantViewModels = new List<INamedTypeSymbol>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var symbol in viewModelSymbols)
        {
            if (!IsViewModelCandidate(symbol, compilation, options))
            {
                continue;
            }

            if (seen.Add(symbol))
            {
                relevantViewModels.Add(symbol);
            }
        }

        relevantViewModels.Sort(static (left, right) =>
            string.Compare(left.ToDisplayString(), right.ToDisplayString(), StringComparison.Ordinal));

        var source = new StringBuilder(
            $$"""
            // <auto-generated />
            #nullable enable
            using System;
            using System.Collections.Generic;
            using Avalonia.Controls;

            namespace {{namespaceNameLocator}};

            public partial class {{classNameLocator}}
            {
            """);

        source.AppendLine();
        source.AppendLine("\tprivate static Dictionary<Type, Func<Control>> s_views = new()");
        source.AppendLine("\t{");

        var viewBaseTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var userControlViewSymbol = compilation.GetTypeByMetadataName("Avalonia.Controls.UserControl");
        if (userControlViewSymbol is not null)
        {
            viewBaseTypes.Add(userControlViewSymbol);
        }

        var windowViewSymbol = compilation.GetTypeByMetadataName("Avalonia.Controls.Window");
        if (windowViewSymbol is not null)
        {
            viewBaseTypes.Add(windowViewSymbol);
        }

        foreach (var additionalTypeName in options.AdditionalViewBaseTypes)
        {
            var additionalSymbol = compilation.GetTypeByMetadataName(additionalTypeName);
            if (additionalSymbol is not null)
            {
                viewBaseTypes.Add(additionalSymbol);
            }
        }

        foreach (var viewModelSymbol in relevantViewModels)
        {
            var namespaceNameViewModel = viewModelSymbol.ContainingNamespace.ToDisplayString();
            var sourceTypeNameViewModel = GetSourceTypeName(viewModelSymbol);
            var metadataTypeNameViewModel = GetMetadataTypeName(viewModelSymbol);

            var sourceNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);
            var metadataNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);

            var sourceTypeNameView = ApplyReplacementRules(sourceTypeNameViewModel, options.TypeNameReplacementRules);
            var metadataTypeNameView = ApplyReplacementRules(metadataTypeNameViewModel, options.TypeNameReplacementRules);

            if (viewModelSymbol.TypeKind == TypeKind.Interface)
            {
                sourceTypeNameView = StripInterfacePrefix(sourceTypeNameView, options.InterfacePrefixesToStrip);
                metadataTypeNameView = StripInterfacePrefix(metadataTypeNameView, options.InterfacePrefixesToStrip);
            }

            if (options.StripGenericArityFromViewName)
            {
                sourceTypeNameView = StripGenericArity(sourceTypeNameView);
                metadataTypeNameView = StripGenericArity(metadataTypeNameView);
            }

            var classNameViewModel = GetSourceTypeReference(viewModelSymbol);
            var classNameView = $"{sourceNamespaceView}.{sourceTypeNameView}";
            var metadataNameView = $"{metadataNamespaceView}.{metadataTypeNameView}";

            var viewSymbol = compilation.GetTypeByMetadataName(metadataNameView);
            var isSupportedView = false;
            if (viewSymbol is not null && viewBaseTypes.Count > 0)
            {
                for (var current = viewSymbol; current is not null; current = current.BaseType)
                {
                    if (viewBaseTypes.Contains(current))
                    {
                        isSupportedView = true;
                        break;
                    }
                }
            }

            if (viewSymbol is null || !isSupportedView)
            {
                continue;
            }

            if (viewSymbol.IsGenericType)
            {
                continue;
            }

            source.AppendLine($"\t\t[typeof({classNameViewModel})] = () => new {classNameView}(),");
        }

        source.AppendLine("\t};");
        source.AppendLine();
        source.AppendLine("\tprivate static Dictionary<Type, string> s_missingViews = new()");
        source.AppendLine("\t{");

        foreach (var viewModelSymbol in relevantViewModels)
        {
            var namespaceNameViewModel = viewModelSymbol.ContainingNamespace.ToDisplayString();
            var sourceTypeNameViewModel = GetSourceTypeName(viewModelSymbol);
            var metadataTypeNameViewModel = GetMetadataTypeName(viewModelSymbol);

            var sourceNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);
            var metadataNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);

            var sourceTypeNameView = ApplyReplacementRules(sourceTypeNameViewModel, options.TypeNameReplacementRules);
            var metadataTypeNameView = ApplyReplacementRules(metadataTypeNameViewModel, options.TypeNameReplacementRules);

            if (viewModelSymbol.TypeKind == TypeKind.Interface)
            {
                sourceTypeNameView = StripInterfacePrefix(sourceTypeNameView, options.InterfacePrefixesToStrip);
                metadataTypeNameView = StripInterfacePrefix(metadataTypeNameView, options.InterfacePrefixesToStrip);
            }

            if (options.StripGenericArityFromViewName)
            {
                sourceTypeNameView = StripGenericArity(sourceTypeNameView);
                metadataTypeNameView = StripGenericArity(metadataTypeNameView);
            }

            var classNameViewModel = GetSourceTypeReference(viewModelSymbol);
            var classNameView = $"{sourceNamespaceView}.{sourceTypeNameView}";
            var metadataNameView = $"{metadataNamespaceView}.{metadataTypeNameView}";

            var viewSymbol = compilation.GetTypeByMetadataName(metadataNameView);
            var isSupportedView = false;
            if (viewSymbol is not null && viewBaseTypes.Count > 0)
            {
                for (var current = viewSymbol; current is not null; current = current.BaseType)
                {
                    if (viewBaseTypes.Contains(current))
                    {
                        isSupportedView = true;
                        break;
                    }
                }
            }

            if (viewSymbol is not null && isSupportedView)
            {
                continue;
            }

            source.AppendLine(
                $"\t\t[typeof({classNameViewModel})] = \"Not Found: {classNameView}\",");
        }

        source.AppendLine("\t};");

        if (!buildMethodExists)
        {
            source.Append(
                """

	public Control? Build(object? data)
	{
		if (data is null)
		{
			return null;
		}

		var type = data.GetType();
		var func = TryGetFactory(type) ?? TryGetFactoryFromInterfaces(type);

		if (func is not null)
		{
			return func.Invoke();
		}

		var missingView = TryGetMissingView(type) ?? TryGetMissingViewFromInterfaces(type);
		if (missingView is not null)
		{
			return new TextBlock { Text = missingView };
		}

		throw new Exception($"Unable to create view for type: {type}");
	}

""");
        }

        source.Append(
            """

	private static Func<Control>? TryGetFactory(Type? type)
	{
		if (type is null)
		{
			return null;
		}

		if (TryGetFactoryForType(type, out var func))
		{
			return func;
		}

		for (var current = type.BaseType; current is not null; current = current.BaseType)
		{
			if (TryGetFactoryForType(current, out func))
			{
				return func;
			}
		}

		return null;
	}

	private static Func<Control>? TryGetFactoryFromInterfaces(Type type)
	{
		var interfaces = type.GetInterfaces();
		for (var index = interfaces.Length - 1; index >= 0; index--)
		{
			var interfaceType = interfaces[index];
			if (!interfaceType.Name.EndsWith("ViewModel", StringComparison.Ordinal))
			{
				continue;
			}

			if (TryGetFactoryForType(interfaceType, out var func))
			{
				return func;
			}
		}

		return null;
	}

	private static bool TryGetFactoryForType(Type type, out Func<Control>? func)
	{
		if (s_views.TryGetValue(type, out func))
		{
			return true;
		}

		if (type.IsGenericType && s_views.TryGetValue(type.GetGenericTypeDefinition(), out func))
		{
			return true;
		}

		func = null;
		return false;
	}

	private static string? TryGetMissingView(Type? type)
	{
		if (type is null)
		{
			return null;
		}

		if (TryGetMissingViewForType(type, out var missingView))
		{
			return missingView;
		}

		for (var current = type.BaseType; current is not null; current = current.BaseType)
		{
			if (TryGetMissingViewForType(current, out missingView))
			{
				return missingView;
			}
		}

		return null;
	}

	private static string? TryGetMissingViewFromInterfaces(Type type)
	{
		var interfaces = type.GetInterfaces();
		for (var index = interfaces.Length - 1; index >= 0; index--)
		{
			var interfaceType = interfaces[index];
			if (!interfaceType.Name.EndsWith("ViewModel", StringComparison.Ordinal))
			{
				continue;
			}

			if (TryGetMissingViewForType(interfaceType, out var missingView))
			{
				return missingView;
			}
		}

		return null;
	}

	private static bool TryGetMissingViewForType(Type type, out string? missingView)
	{
		if (s_missingViews.TryGetValue(type, out missingView))
		{
			return true;
		}

		if (type.IsGenericType && s_missingViews.TryGetValue(type.GetGenericTypeDefinition(), out missingView))
		{
			return true;
		}

		missingView = null;
		return false;
	}

""");

        source.AppendLine("}");

        return source.ToString();
    }
}
